### ISSUE TITLE
Build failed with an exception.

### ISSUE THREAD

**Issue by meridorkobi** [yanisalfian/flutter-phone-direct-caller#19]
Hi,
What is the problem?
Thanks

*** Where:**

`Build file 'C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_phone_direct_caller-2.1.0\android\build.gradle' line: 12

*** What went wrong:**

```
A problem occurred evaluating project ':flutter_phone_direct_caller'.
> Could not get unknown property 'kotlin_version' for object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

```

**Comment by maheshts** [comment]
i am also facing same issue

**Comment by yanisalfian** [comment]
@meridorkobi could you share your project's ```build.gradle``` file? (the one inside ```android``` folder)

**Comment by PrincEddy** [comment]
buildscript {
    repositories {
        google()
        jcenter()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:4.0.0'
    }
}

allprojects {
    repositories {
        google()
        jcenter()
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

task clean(type: Delete) {
    delete rootProject.buildDir
}

**Comment by yanisalfian** [comment]
Thanks @PrincEddy  for replying

Can you change pub dependency in ```pubspec.yaml``` to use the fix from github and see whether the error still exists?

```
dependencies: 
  ...
  flutter_phone_direct_caller:
    git:
      url: https://github.com/yanisalfian/flutter-phone-direct-caller.git
      ref: fix/issue#19
  ...
```
