### ISSUE TITLE
🚑 Not Working On IOS 18

### ISSUE THREAD

**Issue by ibraheemalayan** [yanisalfian/flutter-phone-direct-caller#44]
The library is no longer working on IOS 18 because it uses a previously deprecated API ( completely removed in IOS 18 )

I fixed it and created a pull request ( #43 ).

Until this pull request is merged into the main branch, for anyone interested in the fix, you can install it from this pull request by putting the following in your `pubspec.yml`

replace 
```
  flutter_phone_direct_caller: ^2.1.1
```
with
```
flutter_phone_direct_caller:
    git:
      url: https://github.com/ibraheemalayan/flutter-phone-direct-caller.git
      ref: 4d859e1 # commit hash
```
